### ISSUE TITLE
天气和热门微博账户过期

### ISSUE THREAD

**Issue by st1ven** [1pone/1pone.github.io#11]
如图：
![image](https://user-images.githubusercontent.com/33983147/146698257-322bf1ff-37d1-4a3a-b509-ee4ed5f5a16d.png)
![image](https://user-images.githubusercontent.com/33983147/146698268-cfed7da0-65ff-4fb6-9c54-aa0d034a3b24.png)
最后非常感谢这个项目，让我的kindle焕发第二春！

**Comment by 1pone** [comment]
已续费
