### ISSUE TITLE
Kindle Paperwhite 1 无法打开 1pone.github.io 网页

### ISSUE THREAD

**Issue by davidzwb** [1pone/1pone.github.io#12]
Kindle Paperwhite 1，固件版本 5.4.4.2
输入网址后显示：There was a problem loading this page.
使用同样网络，在手机上可以打开这个页面。
http://k.ilib.io/u/clock.html 等网络时钟也可以打开。

**Comment by 1pone** [comment]
我的kindle之前也偶尔出现过这个问题，过一段时间就好了，原因暂时未知，你可以重启一下或者过段时间观察一下
