### ISSUE TITLE
天气加载不出来

### ISSUE THREAD

**Issue by tlanks** [1pone/1pone.github.io#17]
一直是“天气加载中”

**Comment by luoxufeiyan** [comment]
同样出现这个问题

**Comment by luoxufeiyan** [comment]
看了一下，报错是 API 提示 `key错误或为空`，可能是作者的API KEY达到调用上限或者 API KEY 被更新了。

可以自己在[天行数据](https://www.tianapi.com/apiview/43)这里申请一个API，在 `main.js` 里替换 `TIANAPI` 值，减轻一下作者的 API KEY 压力。

**Comment by 1pone** [comment]
API KEY 已更新
想要稳定使用的朋友可以 fork 一份代码并使用自己申请的 API KEY

**Comment by luoxufeiyan** [comment]
谢谢！
