### ISSUE TITLE
20天后 天气再次处于加载中

### ISSUE THREAD

**Issue by lithiumleeow** [1pone/1pone.github.io#22]

**Comment by 1pone** [comment]
接口还是不太稳定, 后续可能会提供一个简单的接口token配置页, 取代现在的公共接口以提高稳定性

**Comment by 1pone** [comment]
测试版已添加Key设置页面, 欢迎测试
https://1pone.github.io/beta/

**Comment by bangkibang** [comment]
1月3日实测，github和gitee都无法实现天气和时钟刷新，均显示Na。页内右上角并无显示设置按键，无法调试

**Comment by 1pone** [comment]
> 1月3日实测，github和gitee都无法实现天气和时钟刷新，均显示Na。页内右上角并无显示设置按键，无法调试

已修复，再试一下
