### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by xiaoqiangjun** [1pone/1pone.github.io#3]
学长你好啊，在朋友圈看到你的项目，的确很棒哈，我有几点小的建议，你看看有无帮助。  

1. 关于时区，看了源码里对Kindle的解决方案，顺着那个思路的话，[这个网址](http://worldtimeapi.org/api/ip)可以提供当前ip时区信息。
2. 但是为了获取时区再一次访问网络其实不值当，我的一个想法是**做一个”设置页“**，用户自己选择timezoneoffset，顺便还可以设置地区或者微博条数什么的，保存时存到cookies里。
3. api接口问题，用集成的肯定限制比较多，有很多单独功能的接口会更好用，比如[一言](https://pa-1251215871.cos-website.ap-chengdu.myqcloud.com/sentence/)，[今日诗词](https://www.jinrishici.com/)，[unsplash随机图片](https://source.unsplash.com/random)，另一个更快的[随机图片](https://picsum.photos/)，[今日必应图片](https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=zh-CN)
4. 关于天气我也不知道有啥免费好用的，关于微博热搜……

**Comment by 1pone** [comment]
小强君你好呀，很高兴收到你的建议：
1. [这个网站](http://worldtimeapi.org/api/ip)配合cookie应该可以完美解决时区问题。
2. 关于**设置页**之前也有过这样的想法，但是我还是决定让一切尽量简单优雅，能自动设置的就不添加手动设置的页面了，这也是在2.0里通过点击不同组件进行组件配置切换的指导思想，这样的效果就是将**设置页**隐藏在**主页**当中。不过如果后续随着功能不断增加，自定义的需求不断增大，那时候再添加设置页也许在所难免。
3. 你提供的这些接口都非常的棒，之前因为在开发测试阶段频繁调用一些公共免费接口可能会有所受限，不过等正式上线后这种接口应该是更好更长久的选择。
4. 关于你说的直接解析微博指的是爬虫么？如果是后端来做那是没什么问题，相当于自己来做服务器接口，但这样并没有差别；如果是在纯前端浏览器环境下做爬虫这我就不太了解了，不知道会不会有跨域的限制，如果你有好的解决方法欢迎pull request。
感谢你耐心阅读源码并提供宝贵实用的建议～

**Comment by 1pone** [comment]
小强君你好呀，很高兴收到你的建议：
1. [这个网站](http://worldtimeapi.org/api/ip)配合cookie应该可以完美解决时区问题。
2. 关于**设置页**之前也有过这样的想法，但是我还是决定让一切尽量简单优雅，能自动设置的就不添加手动设置的页面了，这也是在2.0里通过点击不同组件进行组件配置切换的指导思想，这样的效果就是将**设置页**隐藏在**主页**当中。不过如果后续随着功能不断增加，自定义的需求不断增大，那时候再添加设置页也许在所难免。
3. 你提供的这些接口都非常的棒，之前因为在开发测试阶段频繁调用一些公共免费接口可能会有所受限，不过等正式上线后这种接口应该是更好更长久的选择。
4. 关于你说的直接解析微博指的是爬虫么？如果是后端来做那是没什么问题，相当于自己来做服务器接口，但这样并没有差别；如果是在纯前端浏览器环境下做爬虫这我就不太了解了，不知道会不会有跨域的限制，如果你有好的解决方法欢迎pull request。

感谢你耐心阅读源码并提供宝贵实用的建议～

**Comment by xiaoqiangjun** [comment]
我天真了，昨晚我以为我已经搞懂了”跨域“是什么，今天碰壁后仔细搜索学了下，发现不行，确实会跨域哈哈
