### ISSUE TITLE
希望构建中国镜像

### ISSUE THREAD

**Issue by ustcdzy** [1pone/1pone.github.io#4]
你好，看到了你的这个项目，奈何国内访问GitHub不定时抽风。我想给你的网站建立一个国内镜像，一方面方便我自己使用，另一方面方便其他国内用户使用。如果可以，请联系我。

**Comment by 1pone** [comment]
你好，我在gitee上其实也是有镜像的，不过不一定会和GitHub完全同步。https://gitee.com/wellpeng/wellpeng

**Comment by ustcdzy** [comment]
好的，看到了，gitee上的速度快了很多
