### ISSUE TITLE
请问天气用的什么api

### ISSUE THREAD

**Issue by qiaoborui** [1pone/1pone.github.io#5]
西安的天气数据差的有点远

**Comment by 1pone** [comment]
http://alapi.cn
数据一直都不对么

**Comment by qiaoborui** [comment]
对的，和实际温度差了挺多> http://alapi.cn
> 
> 数据一直都不对么

**Comment by 1pone** [comment]
> 对的，和实际温度差了挺多> http://alapi.cn
> 
> > 数据一直都不对么

那你看看天气上面显示的城市是你所在的城市么？或者你有没有用vpn影响到了你的IP，因为是根据你的客户端IP判断所在城市。再不行你就登陆上面这个网站手动测试一下API，如果还是不准应该就是API的问题吧。
