### ISSUE TITLE
天气接口异常

### ISSUE THREAD

**Issue by non-one** [1pone/1pone.github.io#9]
V2显示的温度不准确，V1倒是正常，可以看到接口返回的数据是错的
![image](https://user-images.githubusercontent.com/32992657/136578886-5cc94ea6-d3b1-4fa8-9128-964d0caea9a9.png)
西安。。黑龙江。。
emmm
PS. gitee上打开的页面还是V1版本，可能是缓存问题，希望更新下

**Comment by 1pone** [comment]
v2与v1采用不同接口，天气气温等不准确应该是接口问题
另，gitee版本已更新
